-- 코드를 입력하세요
# SELECT a.PRODUCT_CODE, (a.PRICE * b.SALES_AMOUNT) as SALES
# FROM PRODUCT a 
# RIGHT JOIN OFFLINE_SALE b
# USING (PRODUCT_ID)
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, PRODUCT_CODE

SELECT product_code, sum(SALES_AMOUNT*PRICE) as SALES
from PRODUCT
inner join OFFLINE_SALE 
USING(product_id)
group by product_code
order by SALES DESC, PRODUCT_CODE ASC