WITH T as (
    SELECT MAX(SIZE_OF_COLONY) as TOP, YEAR(MAX(DIFFERENTIATION_DATE)) as d
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    )

SELECT T.d as YEAR, T.TOP-e.SIZE_OF_COLONY as YEAR_DEV, e.ID
FROM ECOLI_DATA e
JOIN T
ON YEAR(e.DIFFERENTIATION_DATE) = T.d
ORDER BY YEAR, YEAR_DEV