a = input()
a = a.replace('c=','c')
a = a.replace('c-','c')
a = a.replace('dz=','d')
a = a.replace('d-','d')
a = a.replace('lj','l')
a = a.replace('nj','n')
a = a.replace('s=','s')
a = a.replace('z=','z')
print(len(a))